import { defineField, defineType } from "sanity";

export const product = defineType({
  name: "product",
  title: "Product",
  type: "document",
  groups: [
    { name: "hero", title: "Hero", default: true },
    { name: "content", title: "Content" },
    { name: "related", title: "Cross-references" },
    { name: "cta", title: "CTA-band" },
    { name: "seo", title: "SEO" },
    { name: "notes", title: "Extra notities" },
  ],
  fields: [
    defineField({ name: "language", type: "string", readOnly: true, hidden: true }),
    defineField({
      name: "title",
      type: "string",
      validation: (Rule) => Rule.required(),
      group: "hero",
      description: "Korte documenttitel (Studio, metadata-fallback)",
    }),
    defineField({
      name: "slug",
      type: "slug",
      options: { source: "title", maxLength: 96 },
      validation: (Rule) => Rule.required(),
      group: "hero",
    }),
    defineField({
      name: "heroEyebrow",
      title: "Hero — eyebrow",
      type: "string",
      group: "hero",
    }),
    defineField({
      name: "heroHeadline",
      title: "Hero — hoofdlijn (H1)",
      type: "string",
      description: "Één regel; voor meerdere regels gebruik u handmatige line-break in Studio indien nodig",
      group: "hero",
    }),
    defineField({
      name: "heroIntro",
      title: "Hero — intro",
      type: "text",
      rows: 5,
      group: "hero",
    }),
    defineField({ name: "heroPrimaryCta", title: "Hero — primaire CTA", type: "cta", group: "hero" }),
    defineField({ name: "heroSecondaryCta", title: "Hero — secundaire CTA", type: "cta", group: "hero" }),
    defineField({
      name: "heroImage",
      title: "Hero — beeld",
      type: "imageWithAlt",
      description: "Optioneel — zonder beeld toont de site een donkere placeholder",
      group: "hero",
    }),
    defineField({
      name: "specifications",
      title: "Specificaties",
      type: "array",
      group: "content",
      of: [
        {
          type: "object",
          fields: [
            defineField({ name: "title", type: "string", validation: (r) => r.required() }),
            defineField({ name: "body", type: "text", rows: 4 }),
            defineField({
              name: "icon",
              type: "string",
              title: "Icon / accent",
              description: "Optioneel (emoji of korte code)",
            }),
          ],
        },
      ],
    }),
    defineField({
      name: "applications",
      title: "Toepassingen (tags)",
      type: "array",
      of: [{ type: "string" }],
      group: "content",
    }),
    defineField({
      name: "whyHobonTitle",
      title: "Waarom Hobon — titel",
      type: "string",
      initialValue: "Waarom Hobon",
      group: "content",
    }),
    defineField({
      name: "whyHobonBody",
      title: "Waarom Hobon — tekst",
      type: "text",
      rows: 6,
      group: "content",
    }),
    defineField({
      name: "relatedSectors",
      title: "Gerelateerde sectoren",
      description: "Voor blok “Veel gebruikt in” op de productpagina",
      type: "array",
      group: "related",
      of: [{ type: "reference", to: [{ type: "sector" }] }],
    }),
    defineField({
      name: "ctaBandTitle1",
      title: "CTA-band — titel",
      type: "string",
      group: "cta",
    }),
    defineField({
      name: "ctaBandBody",
      title: "CTA-band — body",
      type: "text",
      rows: 4,
      group: "cta",
    }),
    defineField({
      name: "ctaBandPrimary",
      title: "CTA-band — knop",
      type: "object",
      group: "cta",
      fields: [
        defineField({ name: "label", type: "string", validation: (r) => r.required() }),
        defineField({
          name: "href",
          type: "string",
          title: "URL of pad",
          validation: (r) => r.required(),
        }),
      ],
    }),
    defineField({ name: "seo", title: "SEO", type: "seo", group: "seo" }),
    defineField({
      name: "additionalNotes",
      title: "Extra notities (optioneel)",
      type: "richText",
      description: "Vrije tekst voor copywriters — niet opgenomen in de hoofdtemplate",
      group: "notes",
    }),
  ],
});
