import { defineField, defineType } from "sanity";

export const product = defineType({
  name: "product",
  title: "Product",
  type: "document",
  groups: [
    { name: "hero", title: "Hero", default: true },
    { name: "listing", title: "Overzichtspagina" },
    { name: "content", title: "Content" },
    { name: "related", title: "Cross-references" },
    { name: "cta", title: "CTA-band" },
    { name: "seo", title: "SEO" },
    { name: "notes", title: "Extra notities" },
  ],
  fields: [
    defineField({ name: "language", type: "string", readOnly: true, hidden: true }),
    defineField({
      name: "title",
      type: "string",
      validation: (Rule) => Rule.required(),
      group: "hero",
      description: "Korte documenttitel (Studio, metadata-fallback)",
    }),
    defineField({
      name: "slug",
      type: "slug",
      options: { source: "title", maxLength: 96 },
      validation: (Rule) => Rule.required(),
      group: "hero",
    }),
    defineField({
      name: "heroEyebrow",
      title: "Hero — eyebrow",
      type: "string",
      group: "hero",
    }),
    defineField({
      name: "heroHeadline",
      title: "Hero — hoofdlijn (H1)",
      type: "string",
      description: "Één regel; voor meerdere regels gebruik u handmatige line-break in Studio indien nodig",
      group: "hero",
    }),
    defineField({
      name: "heroIntro",
      title: "Hero — intro",
      type: "text",
      rows: 5,
      group: "hero",
    }),
    defineField({ name: "heroPrimaryCta", title: "Hero — primaire CTA", type: "cta", group: "hero" }),
    defineField({ name: "heroSecondaryCta", title: "Hero — secundaire CTA", type: "cta", group: "hero" }),
    defineField({
      name: "heroImage",
      title: "Hero — beeld",
      type: "imageWithAlt",
      description: "Optioneel — zonder beeld toont de site een donkere placeholder",
      group: "hero",
    }),
    defineField({
      name: "heroThumbs",
      title: "Hero — fotostrip",
      type: "array",
      group: "hero",
      of: [{ type: "heroThumb" }],
      description: "Kleine beelden rechts in de hero (zoals sectorpagina’s). Elk item: upload + alt via imageWithAlt.",
    }),
    defineField({
      name: "listingEyebrow",
      title: "Overzicht — label",
      type: "string",
      description: "Korte regel boven de titel op /producten (bijv. “Product · …”)",
      group: "listing",
    }),
    defineField({
      name: "listingDescription",
      title: "Overzicht — teaser",
      type: "text",
      rows: 3,
      description: "1–2 zinnen, scanbaar op de producten-overzichtspagina",
      group: "listing",
      validation: (Rule) => Rule.max(220).warning("Houd de teaser kort (±160 tekens)"),
    }),
    defineField({
      name: "showInOverview",
      title: "Tonen op overzichtspagina",
      type: "boolean",
      initialValue: true,
      description: "Uit voor nicheproducten die niet in de hoofdlijst op /producten horen",
      group: "listing",
    }),
    defineField({
      name: "specifications",
      title: "Specificaties",
      type: "array",
      group: "content",
      of: [
        {
          type: "object",
          fields: [
            defineField({ name: "title", type: "string", validation: (r) => r.required() }),
            defineField({ name: "body", type: "text", rows: 4 }),
            defineField({
              name: "icon",
              type: "string",
              title: "Icon / accent",
              description: "Optioneel (emoji of korte code)",
            }),
          ],
        },
      ],
    }),
    defineField({
      name: "applications",
      title: "Toepassingen (tags)",
      type: "array",
      of: [{ type: "string" }],
      group: "content",
    }),
    defineField({
      name: "solutionsTitle",
      title: "Titel — varianten/kaarten",
      type: "string",
      group: "content",
      description: "Kop boven de oplossingskaarten (bijv. \"Folie op maat\"). Leeg = standaardlabel uit uiLabels.",
    }),
    defineField({
      name: "solutionCards",
      title: "Varianten / oplossingskaarten",
      type: "array",
      group: "content",
      of: [{ type: "solutionCard" }],
      description:
        "Foto-kaarten met titel en omschrijving (bijv. Krimphoezen onder Stretch hood). Geen num/tags/cta verplicht op product.",
    }),
    defineField({
      name: "galleryTitle",
      title: "Titel — fotogalerij",
      type: "string",
      group: "content",
      description: "Kop boven de galerij (bijv. \"In de praktijk\"). Leeg = standaardlabel uit uiLabels. Geen klantnaam.",
    }),
    defineField({
      name: "productGallery",
      title: "Fotogalerij",
      type: "array",
      group: "content",
      of: [{ type: "imageWithAlt" }],
      description: "Productfoto’s met alt-tekst. Geen klantnaam-veld.",
    }),
    defineField({
      name: "faqs",
      title: "Veelgestelde vragen",
      type: "array",
      group: "content",
      of: [{ type: "faqItem" }],
      description: "Accordeon op de productpagina (vraag + antwoord).",
    }),
    defineField({
      name: "whyHobonTitle",
      title: "Waarom Hobon — titel",
      type: "string",
      initialValue: "Waarom Hobon",
      group: "content",
    }),
    defineField({
      name: "whyHobonBody",
      title: "Waarom Hobon — tekst",
      type: "text",
      rows: 6,
      group: "content",
    }),
    defineField({
      name: "relatedSectors",
      title: "Gerelateerde sectoren",
      description:
        "References naar sector-documenten voor het “Folie voor” / “Veel gebruikt in”-grid. Geen inline sector-data.",
      type: "array",
      group: "related",
      of: [{ type: "reference", to: [{ type: "sector" }] }],
    }),
    defineField({
      name: "ctaBandTitle1",
      title: "CTA-band — titel",
      type: "string",
      group: "cta",
    }),
    defineField({
      name: "ctaBandBody",
      title: "CTA-band — body",
      type: "text",
      rows: 4,
      group: "cta",
    }),
    defineField({
      name: "ctaBandPrimary",
      title: "CTA-band — knop",
      type: "object",
      group: "cta",
      fields: [
        defineField({ name: "label", type: "string", validation: (r) => r.required() }),
        defineField({
          name: "href",
          type: "string",
          title: "URL of pad",
          validation: (r) => r.required(),
        }),
      ],
    }),
    defineField({ name: "seo", title: "SEO", type: "seo", group: "seo" }),
    defineField({
      name: "additionalNotes",
      title: "Extra notities (optioneel)",
      type: "richText",
      description: "Vrije tekst voor copywriters — niet opgenomen in de hoofdtemplate",
      group: "notes",
    }),
  ],
});
